### ISSUE TITLE
EPIC array dataset

### ISSUE THREAD

**Issue by ariadnacilleros** [charlesbreeze/eFORGE#18]
Hi!

I am currently running some analyses with eFORGE, but having more than 1,000 CpGs I can not perform them on the web tool, therefore I am using the tool downloaded from this repository. But, comparing with the web tool, I have noticed that in this version there is no EPIC array dataset, is that possible? Are you planning to upload it here as well?

Thank you!

Ariadna

**Comment by charlesbreeze** [comment]
Hi Ariadna,

Thank you for your question.

eFORGE v2.0 works with EPIC/850k datasets, I have added this to the information at https://github.com/charlesbreeze/eFORGE/blob/eforge.v2.0/README 

The files you are looking for are at https://eforge.altiusinstitute.org/?download (these files work with eFORGE v2.0). 

Best,

Charles
